### ISSUE TITLE
Tasks status count should permit to have the count for many statuses

### ISSUE THREAD

**Issue by fdewas-aneo** [aneoconsulting/ArmoniK.Admin.GUI#1039]
When picking tasks status for the `tasks status count component`, the current behaviour is that one color is linked to one status. It would be preferable to have one color for many statuses.
I will try to design some interface for this.

**Comment by Barbapapazes** [comment]
Salut, Est-ce qu'il serait possible d'avoir plus d'informations sur les intentions et la problématique résolue pour l'utilisateur ?

**Comment by fdewas-aneo** [comment]
![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/117363666/011ff900-0237-49f8-b832-a6dc1acf38d4)
Sur ce dialogue (et dans le composant `view-tasks-by-status.component`) il n'y a qu'un statut pour une couleur. Ce qui fait que l'utilisateur ne peut pas, par exemple, grouper les tâches "cancelling" et "cancelled".
Dans l'idée, il faudrait simplement que l'utilisateur puisse sélectionner plusieurs status pour une couleur. On aurait un résultat similaire au `Tasks by status` qu'il y a par défaut sur le dashboard.
