### ISSUE TITLE
Optional type consistency

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK.Admin.GUI#160]
When an optional type is used in the codebase, which one should be used?

- `x?: type`
- `x: type | null`
- `x: type | undefined`

From what I understand, `x?: type` is the best to convey the actual intent, but I have no strong opinion on the matter.

One thing is sure, it should be the same everywhere.

**Comment by esoubiran-aneo** [comment]
yes, `x?: type` is a shortand for `x: type | undefined = undefined` !
