### ISSUE TITLE
Action menu disappear when auto-refresh triggers

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK.Admin.GUI#755]
The action menu for disappear whenever a refresh happens. This makes it very cumbersome to use when the auto-refresh is set-up to a low value like 1s.

![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/91961298/b3d854de-5dda-4162-835c-ecd917abe971)

[v0.10.3](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/releases/tag/v0.10.3)

**Comment by lemaitre-aneo** [comment]
This still happens on 0.10.5

**Comment by Faust1-2was-Aneo** [comment]
found the `recycleRows` tool for tables (what we use to show data). It keeps the rows that have been unchanged, and so shouldn't close the action menu if the object selected is not updated (https://material.angular.io/cdk/table/overview#recyclerows)
