### ISSUE TITLE
Wrong ID in task view

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK.Admin.GUI#757]
The page of a task report the wrong ID in the page title. It shows the session ID instead of the task ID.

![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/91961298/2dfa23b3-6e34-48c8-8b75-18353c1d6595)

[v0.10.3](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/releases/tag/v0.10.3)

**Comment by GunaDinesh** [comment]
fixed in #773

**Comment by Faust1-2was-Aneo** [comment]
Found a pre-implemented tool that recycle unchanged rows in a table: https://material.angular.io/cdk/table/overview#recyclerows
