### ISSUE TITLE
Resources pages are not translated

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK.Admin.GUI#763]
The resource pages (Partitions, Sessions, Tasks, Results) are not translated.

Even more, the Task view page has a mistranslation issue in the title.

![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/91961298/1d0a902e-ca3e-4e61-aff9-8b5d2ac626f3)

[v0.10.3](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/releases/tag/v0.10.3)

**Comment by Faust1-2was-Aneo** [comment]
This might need a new page (and a bit of time) just for this, since now it only displays a json.
