### ISSUE TITLE
Options Options field appears empty while it is not

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK.Admin.GUI#771]
The field Options Options (custom entries in the Task Options) appears empty, but looking at the Options field, the Options sub-field is not empty.

![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/91961298/87d9ab82-c3b8-451a-a71c-4575d9d76a4a)
![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/91961298/9b850c82-b5e1-4340-970b-f86200003d38)

[v0.10.3](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/releases/tag/v0.10.3)

**Comment by GunaDinesh** [comment]
We didn't manage to reproduce the bug.

**Comment by MiveckD** [comment]
Look in Session list page for this issue. 
Options options field doesn't exist for task list page but should
