### ISSUE TITLE
Freeze Application, crash navigateur.

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#876]
Lorsque je vais dans la page de la liste des applications. Lors du refresh de celle-ci. La page plante et le navigateur entier ne répond plus.

![aneo bug 73](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/4cd10cfe-2be9-4bc1-8739-681c5d347ab8)

**Comment by AntonyCanut** [comment]
Il y a des milliers de requetes qui partent sur la base de données lorsque cette page est ouverte.
![Uploading bug aneo 74.png…]()

**Comment by AntonyCanut** [comment]
![bug aneo 74](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/4468a4d9-4c3d-4d17-8ef8-5a23ac529b47)

**Comment by ngruelaneo** [comment]
correct in PR #883
