### ISSUE TITLE
Session visible mais avec aucune valeur 

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#879]
![aneo bug 79](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/4cc3c596-efb8-435c-8c19-cfca680b2b79)
Il y a des sessions qui apparaissent alors qu'elles ne possède aucune valeur (d'ou sortent t'elle ?).

**Comment by ngruelaneo** [comment]
Soit il y a un problème de cache du navigateur soit une session a été créée mais aucunes taches de soumises.
Pourrais tu vérifier ces deux possibilites s'il te plait?

**Comment by AntonyCanut** [comment]
Hello, 
Ce n'est pas un problème de cache. impossible de vérifier le second point pour le moment. Ce serait possible que ce soit ça. Mais l'affichage de cette session fantôme pose un soucis d'utilité.

**Comment by ngruelaneo** [comment]
If it is not a browser cache, the GUI get its informations from the DB. The GUI cannot do anything on the subject.

**Comment by AntonyCanut** [comment]
Du coup, c'est un filtre sur le nombre de task qui est manquant.
Nous avions une demande de filtre sur les tasks qui n'est pas présente.
Nombre de tasks totale <>= Nombre
Nombre task type success <>= Nombre
