### ISSUE TITLE
Filtres ne sont plus fonctionnels

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#880]
Il n'est plus possible de modifier les filtres...
![aneo bug 80](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/ce454e39-081d-4fa0-9ddb-0dc6ebff9255)

**Comment by ngruelaneo** [comment]
Corrected in PR #882
