### ISSUE TITLE
Dans les Tasks, nous n'avons pas besoin d'être aussi dans le temps

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#881]
Le temps de création task pourrait largement suffire s'il n'avait que les secondes dans le tableau.
Le pire est dans le "Creation to End Duration" qui a une précision après la seconde de 6 chiffres. Cela détruit la lisibilité des données
![aneo bug 81](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/913a5d16-049e-4b63-acf3-ab5ad6ed6540)

**Comment by ngruelaneo** [comment]
Other client need to have the ms informations so we kept them but remove the microsecond one. #885
