### ISSUE TITLE
UX : Session, retirer la lourdeur navigation vers la liste des tasks

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#884]
Dans Session, au clic sur un SessionID, nous naviguons vers une page qui représente l'équivalent de "Options" qui ensuite possede des sous-menus :
- See tasks
- See results (a quoi sert cette vue ?)
- See partitions

Dans la précédente GUI, nous navigions vers la liste des Tasks associés à cette session. Plus pratique que la navigation vers des informations non utiles.

**Comment by ngruelaneo** [comment]
Fixed in #885
