### ISSUE TITLE
Applications - Problème refresh

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#886]
0.11.3
L'ordre des applications s'échange avec un refresh naturel (~5secondes) sans réel raison.
Sur 2 applications, la lecture est peu entravé, mais sur plus cela va être un vrai problème.

![1](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/b7bd03c2-8c28-4b3f-a1c6-9afa0ba12a82)
![2](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/40f9f186-003f-4be8-b229-ae717baabd0a)

**Comment by ngruelaneo** [comment]
I can't reproduce it, sorry.

**Comment by AntonyCanut** [comment]
On a creusé et découvert que ça arrive quand le filtre est sur le nom et que plusieurs applications ont le même nom.
