### ISSUE TITLE
Filtre contains sur partition id ne fonctionne pas

### ISSUE THREAD

**Issue by AntonyCanut** [aneoconsulting/ArmoniK.Admin.GUI#889]
Lorsque je veux filtrer les partitions id, je ne dispose que de 2 options :
- contain
- do not contain

Le problème est que contain est compté comme un equal et ne m'affiche pas toutes les idpartitions que je possède.

![6](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/444a2281-5b38-469a-9e66-7f49216d2168)
![7](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/c6d1f4b7-6b9e-4a63-a0a4-781caf2bd3fd)
![8](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/5476562/c905ef99-50a7-4423-aca0-d3f5aea00d8b)

**Comment by ngruelaneo** [comment]
resolved by #890
