### ISSUE TITLE
Rework "External service"

### ISSUE THREAD

**Issue by fdewas-aneo** [aneoconsulting/ArmoniK.Admin.GUI#912]
How services works is not really clear. We need to make it more easy to use

**Comment by Faust1-2was-Aneo** [comment]
What we have:
![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/117363666/4b0bb3cf-185e-448f-b664-d8c86ad4a28e)
![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/117363666/a1dbbee4-82a1-468a-960e-9b3d242e3ead)

We would like to have a more convenient UI and UX for the users:
- A little description of what is an external service,
- There should be two lines for the name and the URL (the URL line should be long enough for the users to see completely).
- We could use an icon picker, located next to the "name" input.

**Comment by Faust1-2was-Aneo** [comment]
Also, this component is not looking good without any external service.
![image](https://github.com/aneoconsulting/ArmoniK.Admin.GUI/assets/117363666/5fdc4cff-bd3b-4fff-a864-856a3bf7174f)

Maybe we want the "Add an external service" dialog to appear directly if there is no external service yet
