### ISSUE TITLE
List of sessions is slow to load

### ISSUE THREAD

**Issue by lemaitre-aneo** [aneoconsulting/ArmoniK.Admin.GUI#98]
![image](https://user-images.githubusercontent.com/91961298/174759902-4ef50dcb-3c31-41f1-b5a5-be9ac6d8a373.png)
![image](https://user-images.githubusercontent.com/91961298/174760016-bb718abe-0099-40f5-91cf-b1d9b58120be.png)

**Comment by esoubiran-aneo** [comment]
Je ne suis pas sûr de savoir quoi faire pour résoudre cette issue
